//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eticaretprojesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Musteri()
        {
            this.Siparis = new HashSet<Siparis>();
            this.Yorumlar = new HashSet<Yorumlar>();
        }
    
        public int Id { get; set; }
        public string adi { get; set; }
        public string Soyadi { get; set; }
        public string Eposta { get; set; }
        public Nullable<System.DateTime> DogumTArihi { get; set; }
        public string Sifre { get; set; }
        public Nullable<int> SepetId { get; set; }
        public Nullable<int> LoginId { get; set; }
        public Nullable<int> SiparisGecmisId { get; set; }
        public string TeslimatAdresi { get; set; }
        public string FaturaAdresi { get; set; }
        public Nullable<int> YorumId { get; set; }
    
        public virtual Login Login { get; set; }
        public virtual SepetId SepetId1 { get; set; }
        public virtual SiparisGecmisi SiparisGecmisi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siparis> Siparis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorumlar> Yorumlar { get; set; }
    }
}
