//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eticaretprojesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SepetId
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SepetId()
        {
            this.musteri = new HashSet<Musteri>();
        }
    
        public int Id { get; set; }
        public Nullable<int> UrunId { get; set; }
        public Nullable<int> VaryantId { get; set; }
        public Nullable<int> Miktari { get; set; }
        public Nullable<decimal> Toplam { get; set; }
        public Nullable<int> OzelikId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Musteri> musteri { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
