//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eticaretprojesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> SatisTarihi { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public Nullable<int> SiparisDurumuId { get; set; }
        public string KargoTakip { get; set; }
        public Nullable<int> OdemeYontemiId { get; set; }
        public Nullable<int> SepetDetayId { get; set; }
    
        public virtual Musteri musteri { get; set; }
        public virtual OdemeYontemi OdemeYontemi { get; set; }
        public virtual SiparisDetay SiparisDetay { get; set; }
        public virtual SiparisDurumu SiparisDurumu { get; set; }
    }
}
