//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eticaretprojesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiparisDetay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SiparisDetay()
        {
            this.Siparis = new HashSet<Siparis>();
        }
    
        public int Id { get; set; }
        public Nullable<int> UrunId { get; set; }
        public Nullable<int> VaryantId { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<int> Miktar { get; set; }
        public Nullable<int> KargoId { get; set; }
        public Nullable<int> OdemeYontemId { get; set; }
        public Nullable<int> OzellikId { get; set; }
    
        public virtual KargoFirmasi KargoFirmasi { get; set; }
        public virtual OdemeYontemi OdemeYontemi { get; set; }
        public virtual Ozellik Ozellik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siparis> Siparis { get; set; }
        public virtual Urunler Urunler { get; set; }
        public virtual Varyant Varyant { get; set; }
    }
}
