//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eticaretprojesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteAyarlari
    {
        public int Id { get; set; }
        public string Telefon { get; set; }
        public string Whatsapp { get; set; }
        public string Adres { get; set; }
        public string Eposta { get; set; }
    }
}
