//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eticaretprojesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urunler()
        {
            this.SepetId = new HashSet<SepetId>();
            this.SiparisDetay = new HashSet<SiparisDetay>();
            this.UrunVaryant = new HashSet<UrunVaryant>();
            this.Yorumlar = new HashSet<Yorumlar>();
        }
    
        public int Id { get; set; }
        public string Adi { get; set; }
        public Nullable<decimal> fiyat { get; set; }
        public string Resim { get; set; }
        public string Aciklama { get; set; }
        public string Stok_Kodu { get; set; }
        public Nullable<int> Adet { get; set; }
        public Nullable<System.DateTime> Ekleme_Tarih { get; set; }
        public Nullable<int> KategoriID { get; set; }
        public Nullable<int> TeslimatId { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SepetId> SepetId { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisDetay> SiparisDetay { get; set; }
        public virtual TeslimatBilgileri TeslimatBilgileri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrunVaryant> UrunVaryant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorumlar> Yorumlar { get; set; }
    }
}
